// Ambient augmentation: expose wrangler.jsonc bindings on the global
// CloudflareEnv interface that @opennextjs/cloudflare's getCloudflareContext() returns.
// Runtime types (D1Database, KVNamespace, Ai) come from
// worker-configuration.d.ts generated by `npm run cf-typegen`.
declare global {
  interface CloudflareEnv {
    DB: D1Database;
    KV: KVNamespace;
    AI: Ai;
    ASSETS: Fetcher;
    /** Workers AI model id override — set as a Worker var/secret. */
    AI_MODEL?: string;
    /** Canonical origin for the sitemap and Open Graph URLs. */
    SITE_URL?: string;
  }
}

export {};
