// Ambient augmentation: expose wrangler.jsonc bindings on the global
// CloudflareEnv interface that @opennextjs/cloudflare's getCloudflareContext() returns.
// Runtime types (D1Database, R2Bucket, KVNamespace, Ai, VectorizeIndex) come from
// worker-configuration.d.ts generated by `npm run cf-typegen`.
declare global {
  interface CloudflareEnv {
    DB: D1Database;
    R2: R2Bucket;
    KV: KVNamespace;
    AI: Ai;
    VEC: VectorizeIndex;
    ASSETS: Fetcher;
    /** Workers AI model id override — set as a Worker var/secret. */
    AI_MODEL?: string;
    /** Shared secret gating the admin routes (vector backfill, stats rollup). */
    ADMIN_TOKEN?: string;
    /** Turnstile site key (public). When unset, bot checks are off. */
    TURNSTILE_SITE_KEY?: string;
    /** Turnstile secret key — always a `wrangler secret`, never a var. */
    TURNSTILE_SECRET_KEY?: string;
  }
}

export {};
