/**
 * Generates drizzle/seed.sql: the five harness fixtures as public gallery
 * designs (scored by the same bundled engine the site runs) plus the curated
 * kits catalog. Applied with `npm run db:seed:local` or `db:seed:remote`.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { evaluate, FIXTURES } from "../src/lib/harness/engine.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(here, "..", "drizzle", "seed.sql");
const now = new Date().toISOString();

function sqlString(v) {
  if (v === null || v === undefined) return "NULL";
  return `'${String(v).replaceAll("'", "''")}'`;
}

const lines = ["-- generated by scripts/seed.mjs — do not edit by hand"];

// Designs: the reconstructions of the first public run
for (const spec of FIXTURES) {
  const report = evaluate(spec);
  const slug = spec.id;
  lines.push(
    `INSERT OR REPLACE INTO designs (id, title, prompt, spec_json, score_json, score_total, gates_passed, model_used, produced_by, remix_of, category, author, likes, views, is_public, created_at) VALUES (` +
      [
        sqlString(slug),
        sqlString(spec.name),
        sqlString(null),
        sqlString(JSON.stringify(spec)),
        sqlString(JSON.stringify(report)),
        report.score.total,
        report.gates.passed ? 1 : 0,
        sqlString(null),
        sqlString(spec.producedBy ?? null),
        sqlString(null),
        sqlString("reference"),
        sqlString("luxobench"),
        0,
        0,
        1,
        sqlString("2026-09-12T00:00:00.000Z"),
      ].join(", ") +
      ");",
  );
}

// Kits: open-source projects with a prebuilt-kit path (the Petoi model)
const kits = [
  {
    id: "opencat-bittle-x",
    name: "OpenCat — Bittle X",
    tagline: "Open-source quadruped robot dog. The framework is free; the kit ships to your door.",
    description:
      "Petoi's OpenCat is the framework behind the Bittle robot dog and Nybble robot cat: gait coordination, servo control and IMU integration on an Arduino/ESP32 board, with Python API, block coding and ROS support on top. 30,000+ robots shipped, 20+ academic papers cite it. This is the model LUXO is aiming at: open-source everything, sell the verified kit. When LUXO gets into the robo biz, this is the benchmark to beat.",
    sourceUrl: "https://github.com/PetoiCamp/OpenCat-Quadruped-Robot",
    kitUrl: "https://www.petoi.com/products/petoi-robot-dog-bittle-x-voice-controlled",
    license: "MIT",
    costNote: "Kit ~$349 (Bittle X). OpenCat code + CAD free on GitHub.",
    featured: true,
    sortOrder: 1,
  },
  {
    id: "adafruit-pygamer",
    name: "Adafruit PyGamer",
    tagline: "Open hardware handheld, sold assembled or as parts — the subassembly model that works.",
    description:
      "Adafruit publishes every PCB and enclosure design file and sells the board legally as a subassembly (FCC 15.101). The proof that the 'sell the parts, not the thing' model from BUSINESS.md runs at scale.",
    sourceUrl: "https://github.com/adafruit/Adafruit_PyGamer",
    kitUrl: "https://www.adafruit.com/product/4242",
    license: "CC-BY-SA / MIT",
    costNote: "Board $44.95; add-your-own enclosure 3D prints.",
    featured: false,
    sortOrder: 2,
  },
  {
    id: "keyboardio-model-100",
    name: "Keyboardio Model 100",
    tagline: "Open-source keyboard shipped as a build-it-yourself kit.",
    description:
      "Kaleidoscope firmware and hardware design files are open; the product ships as a kit the buyer assembles. Buyer supplies the labour, which is exactly why the kit arithmetic in BUSINESS.md beats every other low-volume model.",
    sourceUrl: "https://github.com/keyboardio/Kaleidoscope",
    kitUrl: "https://shop.keyboard.io/",
    license: "GPL/MIT",
    costNote: "Kit ~$349.",
    featured: false,
    sortOrder: 3,
  },
  {
    id: "prusa-mk4s-kit",
    name: "Prusa MK4S (kit form)",
    tagline: "The flagship proof that a hardware kit beats a prebuilt box on margin.",
    description:
      "Prusa ships its printer as a kit — firmware, CAD and docs all open on GitHub. The buyer builds it, saves money, and Prusa keeps margin that would otherwise go to assembly labour. The labour-is-the-product pattern, industrialised.",
    sourceUrl: "https://github.com/prusa3d/Prusa-Firmware",
    kitUrl: "https://www.prusa3d.com/product/original-prusa-mk4s-kit-2/",
    license: "Open (multiple)",
    costNote: "Kit $999 vs $1,199 assembled — the buyer's labour is worth $200.",
    featured: false,
    sortOrder: 4,
  },
];

for (const k of kits) {
  lines.push(
    `INSERT OR REPLACE INTO kits (id, name, tagline, description, source_url, kit_url, license, cost_note, harness_score, featured, sort_order, created_at) VALUES (` +
      [
        sqlString(k.id),
        sqlString(k.name),
        sqlString(k.tagline),
        sqlString(k.description),
        sqlString(k.sourceUrl),
        sqlString(k.kitUrl),
        sqlString(k.license),
        sqlString(k.costNote),
        sqlString(k.harnessScore),
        k.featured ? 1 : 0,
        k.sortOrder,
        sqlString(now),
      ].join(", ") +
      ");",
  );
}

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n") + "\n");
console.log(`Wrote ${outFile} (${FIXTURES.length} designs, ${kits.length} kits)`);
