/**
 * Fixture: the "Magnetic Voice Note-Taker" generated by Blueprint.io.
 *
 * Encoded verbatim from the user's pasted output (13 Sep 2026): the parts list,
 * the stated sources (AliExpress / eBay), the tools, the 16 instruction steps, and
 * the design's own plan. Nothing here is invented; where the source was silent
 * (no PCB, no battery cell) the absence is the finding.
 *
 * The requirement it was asked to satisfy, in the requester's words:
 *   "a device that is a note taker but it is super stylish and understands
 *    everything and listens everything and has a good battery life as well,
 *    should be able to tag to phone on the back and maybe have it easy to use"
 */

import type { ProductSpec, Part, PartType } from '../engine/types.ts';

/**
 * Blueprint listed AliExpress and eBay as the source for every electronic line item.
 * That is not an authorised channel for MCU, analog and regulator class parts.
 */
function blueprintPart(
  id: string,
  label: string,
  partType: PartType,
  qty: number,
  unitPriceUsd: number,
  note: string,
): Part {
  return {
    id,
    label,
    kind: 'catalog',
    process: 'fdm',
    material: 'n/a',
    qty,
    bboxMm: { x: 20, y: 20, z: 5 },
    solidFraction: 0.3,
    purchasePriceUsd: unitPriceUsd / qty,
    source: {
      distributor: 'broker', // AliExpress / eBay as listed
      mpn: id.toUpperCase(),
      inStock: true,
      stockVerified: false,
      alternates: 0,
      partType,
    },
    notes: [note, 'Sourced from AliExpress/eBay as listed by the generator'],
  };
}

export const BLUEPRINT_VOICE_NOTE: ProductSpec = {
  id: 'voice-note-blueprint',
  name: 'Magnetic Voice Note-Taker (Blueprint.io output)',
  intent:
    'Ultra-slim wearable voice note-taker: I2S MEMS mic, BLE MCU, NFC phone pairing, LED status ring, LiPo power, MagSafe back.',
  referenceRender: 'Ultra-slim MagSafe voice recorder with an LED ring and a tactile button.',
  targetRetailUsd: 79,
  targetQuantities: [1, 100, 1000],
  origin: 'china',
  markets: ['us'],
  power: {
    mainsInside: false,
    wireless: 'bluetooth', // BLE pairing was a stated requirement
    battery: 'lithium', // TP4056 charger for a 1S cell
    usbPowered: false,
    externalAdapterCertified: false,
    includesAdapter: false,
    maxWatts: 5,
  },
  features: [
    { id: 'led_ring', label: 'LED status ring', expectedFace: 'top', actualFace: 'top', present: true, cosmetic: true },
    { id: 'button', label: 'Tactile input switch', expectedFace: 'top', actualFace: 'top', present: true, cosmetic: true },
    { id: 'nfc', label: 'NFC tag on the back (phone tap to pair)', expectedFace: 'back', actualFace: 'back', present: true, cosmetic: false },
    { id: 'mic', label: 'Microphone port', expectedFace: 'front', actualFace: 'front', present: true, cosmetic: false },
    {
      id: 'transcription',
      label: 'Understands everything (voice transcription)',
      expectedFace: 'internal',
      present: false,
      cosmetic: false,
      note: 'A stated requirement. The design streams audio over BLE to a phone; no transcription path exists in the BOM or firmware plan.',
    },
    {
      id: 'battery_life',
      label: 'Good battery life (all-day)',
      expectedFace: 'internal',
      present: true,
      cosmetic: false,
      note: 'A stated requirement. The design\'s own AI summary concedes 2-4 hours when streaming, and names no cell capacity.',
    },
  ],
  parts: [
    // --- electronics, all sourced from marketplace channels ---
    blueprintPart('esp32s3', 'Primary MCU (BLE, audio)', 'mcu', 1, 4.5, 'Primary MCU for CSI acquisition in HT40 mode and low-level motor control.'),
    blueprintPart('sph0645', 'I2S MEMS microphone', 'sensor', 1, 2.5, 'Digital I2S MEMS microphone.'),
    blueprintPart('pts645', 'Tactile input switch', 'mechanical', 1, 0.3, 'Actuator.'),
    blueprintPart('tp4056', 'LiPo charger IC', 'regulator', 1, 0.5, 'TP4056-based LiPo charger with USB-C input. Note: listed as an IC, described as a module.'),
    blueprintPart('st25dv', 'NFC tagging module', 'sensor', 1, 1.2, 'ST25DV-I2C NFC module.'),
    blueprintPart('ws2812b', 'LED ring controller', 'led', 8, 1.6, 'RGB LED for visual feedback.'),
    blueprintPart('magnet', 'Neodymium magnet ring (MagSafe)', 'mechanical', 1, 2.0, 'Adhesive-backed magnetic ring.'),
    blueprintPart('screws', 'M1.4 x 4mm countersunk screws', 'mechanical', 4, 0.6, 'Precision screws for the enclosure shells.'),
    // NOTE: no battery cell line item exists, though the TP4056 charges one.
    // NOTE: no PCB line item exists, though the plan says "design a custom PCB"
    // and four wiring steps describe soldering parts together.

    // --- printed parts ---
    { id: 'top_shell', label: 'SLA resin top shell', kind: 'custom', process: 'resin_sla', material: 'resin_std', qty: 1, bboxMm: { x: 70, y: 45, z: 18 }, solidFraction: 0.18, wallMm: 1.2, toleranceMm: 0.2, visibleFaces: ['front', 'back', 'left', 'right', 'top'] },
    { id: 'bottom_shell', label: 'SLA resin bottom shell', kind: 'custom', process: 'resin_sla', material: 'resin_std', qty: 1, bboxMm: { x: 70, y: 45, z: 12 }, solidFraction: 0.2, wallMm: 1.2, toleranceMm: 0.2, visibleFaces: ['front', 'back', 'left', 'right', 'bottom'] },
    { id: 'mcu_mount', label: 'MCU internal mount', kind: 'custom', process: 'resin_sla', material: 'resin_std', qty: 1, bboxMm: { x: 30, y: 25, z: 8 }, solidFraction: 0.25, wallMm: 1.0, toleranceMm: 0.2, visibleFaces: [] },
    { id: 'gasket', label: 'Acoustic sealing gasket (TPU, 100% infill)', kind: 'custom', process: 'fdm', material: 'tpu', qty: 1, bboxMm: { x: 12, y: 12, z: 2 }, solidFraction: 0.9, wallMm: 1.0, toleranceMm: 0.4, visibleFaces: [] },
    { id: 'nfc_mount', label: 'NFC module mount (M3 hardware, per part label)', kind: 'custom', process: 'fdm', material: 'petg', qty: 1, bboxMm: { x: 28, y: 20, z: 6 }, solidFraction: 0.3, wallMm: 1.4, toleranceMm: 0.4, visibleFaces: [] },
    { id: 'led_mount', label: 'LED ring mount', kind: 'custom', process: 'fdm', material: 'petg', qty: 1, bboxMm: { x: 40, y: 40, z: 8 }, solidFraction: 0.3, wallMm: 1.4, toleranceMm: 0.4, visibleFaces: [] },
    { id: 'switch_mount', label: 'Tactile switch mount', kind: 'custom', process: 'fdm', material: 'petg', qty: 1, bboxMm: { x: 16, y: 16, z: 5 }, solidFraction: 0.3, wallMm: 1.4, toleranceMm: 0.4, visibleFaces: [] },
  ],
  interfaces: [
    { id: 'shells', between: ['top_shell', 'bottom_shell'], clearanceMm: 0.4, contributors: ['top_shell', 'bottom_shell'] },
    { id: 'led-to-top', between: ['led_mount', 'top_shell'], clearanceMm: 0.4, contributors: ['led_mount', 'top_shell'] },
  ],
  operations: [
    // 1. Fabricate (3 steps)
    { id: 'op-print-shells', label: 'Print primary enclosure shells in resin', minutes: 15, improvised: false },
    { id: 'op-print-mounts', label: 'Print internal mounts and acoustic gasket', minutes: 15, improvised: false },
    { id: 'op-cure', label: 'Post-process resin parts (clean and cure)', minutes: 30, improvised: false },
    // 2. Wire (4 steps) - soldering a bare SOIC charger and flying leads to a module
    { id: 'op-wire-power', label: 'Solder power distribution to battery management IC', minutes: 25, improvised: true, requiresSoldering: true, wireCount: 4 },
    { id: 'op-wire-i2s', label: 'Wire I2S interface for the microphone', minutes: 20, improvised: true, requiresSoldering: true, wireCount: 4 },
    { id: 'op-wire-nfc', label: 'Connect I2C NFC module to main controller', minutes: 20, improvised: true, requiresSoldering: true, wireCount: 4 },
    { id: 'op-wire-leds', label: 'Solder status indicator and input switch', minutes: 25, improvised: true, requiresSoldering: true, wireCount: 6 },
    // 3. Bring-up (5 steps)
    { id: 'op-continuity', label: 'Continuity and short-circuit test', minutes: 10, improvised: false },
    { id: 'op-flash', label: 'Flash firmware, test LED ring', minutes: 20, improvised: false },
    { id: 'op-i2s', label: 'Verify I2S stream from microphone', minutes: 15, improvised: false },
    { id: 'op-nfc-test', label: 'Validate NFC tag detection over I2C', minutes: 15, improvised: false },
    { id: 'op-debounce', label: 'Calibrate button debounce logic', minutes: 15, improvised: false },
    // 4. Assemble (4 steps)
    { id: 'op-assemble-mounts', label: 'Secure mounts and electronics to bottom shell', minutes: 12, improvised: false },
    { id: 'op-assemble-top', label: 'Install switch and indicator into top shell', minutes: 12, improvised: false },
    { id: 'op-magnet', label: 'Affix magnet ring to base', minutes: 5, improvised: false },
    { id: 'op-close', label: 'Close enclosure with 4 screws', minutes: 8, improvised: false },
  ],
  certificationsBudgeted: [], // none listed anywhere in the output
  requiresSignedDrivers: false,
  // The instruction set says "Flash firmware and test LED status indicator", but the
  // output ships no firmware. The step exists; the artifact does not.
  firmware: { provided: false },
  costDisclosed: true, // line prices are published; the total excludes PCB, cell, tools and shipping
  cad: { opensClean: true, watertight: true, requiresManualRepair: false, ercClean: true, drcClean: true },
  producedBy: 'Blueprint.io (3E8 Robotics)',
  provenance:
    'Encoded from the user\'s pasted Blueprint.io output, 13 Sep 2026. Tools required by the design itself: SLA printer, FDM printer, soldering iron, multimeter, flush cutters, tweezers, UV curing station - none of which appear in the parts cost.',
};
